plugins {
    id 'multiloader-loader'
    id 'eclipse'
    id 'idea'
    id 'net.neoforged.moddev'
    id 'net.darkhax.curseforgegradle'
    id 'com.modrinth.minotaur'
}

base {
    archivesName = "${mod_archives_name}-neoforge-${minecraft_version}-${mod_version}"
}

repositories {
    maven {
        name = 'CurseMaven'
        url = 'https://www.cursemaven.com'
    }
    maven {
        name = 'ParchmentMC'
        url = 'https://maven.parchmentmc.org/'
    }
    maven {
        url "https://maven.sighs.cc/repository/maven-releases/"
    }
    maven {
        url "https://maven.sighs.cc/repository/maven-snapshots/"
    }
}

dependencies {
    implementation 'cc.sighs.oelib:oelib-neoforge-1.21.1:0.3.0-SNAPSHOT'
}

def changelogText = rootProject.file('changelog.md').text

neoForge {
    version = neoforge_version

    def at = file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }

    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }

    runs {
        configureEach {
            systemProperty 'neoforge.enabledGameTestNamespaces', mod_id
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})"
        }

        client {
            client()
            gameDirectory = file('runs/client')
            programArguments.addAll '--username', 'Dev'
        }

        clientAlt {
            client()
            gameDirectory = file('runs/client2')
            programArguments.addAll '--username', 'Dev2'
        }

        server {
            server()
            gameDirectory = file('runs/server')
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

java {
    toolchain.languageVersion.set(JavaLanguageVersion.of(java_version))
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release.set(java_version as Integer)
}

jar {
    manifest {
        attributes([
                'Specification-Title'      : mod_id,
                'Specification-Vendor'     : mod_authors,
                'Specification-Version'    : '4',
                'Implementation-Title'     : mod_display_name,
                'Implementation-Version'   : mod_version,
                'Implementation-Vendor'    : mod_authors,
                'Implementation-Timestamp' : new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
                'Built-On-Minecraft'       : minecraft_version
        ])
    }
}

processResources {
    filesMatching(['META-INF/neoforge.mods.toml', 'pack.mcmeta']) {
        expand project.properties
    }
    outputs.upToDateWhen {
        false
    }
}

modrinth {
    token.set(System.getenv('MODRINTH_TOKEN'))
    projectId.set(modrinth_project_id)
    changelog.set(changelogText)
    versionNumber.set(mod_version)
    versionName.set("${mod_display_name} ${mod_version}")
    versionType.set('release')
    uploadFile.set(file("build/libs/${mod_archives_name}-neoforge-${minecraft_version}-${mod_version}.jar"))
    gameVersions.set([minecraft_version])
    loaders.set(['neoforge'])
}

task curseforge(type: net.darkhax.curseforgegradle.TaskPublishCurseForge) {
    dependsOn 'build'
    group = 'publishing'
    apiToken = System.getenv('CURSEFORGE_TOKEN')

    def file = upload(curseforge_project_id, file("build/libs/${mod_archives_name}-neoforge-${minecraft_version}-${mod_version}.jar"))
    file.displayName = "${mod_display_name} ${mod_version} (NeoForge)"
    file.changelog = changelogText
    file.changelogType = 'markdown'
    file.addModLoader('NeoForge')
    file.addGameVersion(minecraft_version)
    file.addGameVersion('Client', 'Server')
    file.addJavaVersion('Java 21')
    file.releaseType = 'release'
}

tasks.register('publishMods') {
    group = 'publishing'
    if (!mod_version.contains('unfinished')) {
        dependsOn tasks.named('modrinth')
        dependsOn tasks.named('curseforge')
    } else {
        logger.error('Tried to publish unfinished mod')
    }
}
